project:
  type: book

book:
  title: "Apuntes de programación en Rust"
  author: "Miguel A. Ortuño Pérez"
  date: today
  chapters:
    - index.qmd
    - 02-intro_rust.qmd
    - 03-entorno.qmd
    - 04-fundamentos.qmd
    - 05-vbles-ctes-tbasicos.qmd
    - 06-tipos_compuestos.qmd
    - 07-funciones.qmd
    - 08-control_flujo.qmd
    - 09-propiedad.qmd
    - 10-structs.qmd
    - 11-metodos.qmd
    - 12-enum.qmd
    - 13-patrones.qmd
    - 14-colecciones.qmd
    - 15-genericos.qmd



lang: es-ES

language:
  title-block-author-single: "Autor"
  title-block-author-plural: "Autores"

crossref:
  chapters: true

format:
  html:
    toc: true
    number-sections: true
    code-copy: true

  pdf:
    documentclass: scrreprt
    classoption:
      - twoside

    fontsize: 12pt

    geometry:
      - top=2cm
      - bottom=2cm
      - left=2.2cm
      - right=2.2cm

    highlight-style: tango
    linestretch: 1.05
    number-sections: true
    papersize: a4
    pdf-engine: xelatex

    toc: true
    toc-title: Índice

    lot: true

    include-in-header:
      text: |
        \usepackage{fancyhdr}

        \pagestyle{fancy}
        \fancyhf{}

        % Título del libro en páginas pares
        \fancyhead[LE]{Apuntes de programación en Rust}

        % Capítulo actual en páginas impares
        \fancyhead[RO]{\nouppercase{\leftmark}}

        % Número de página en el exterior
        \fancyhead[RE,LO]{\thepage}

        \renewcommand{\headrulewidth}{0.4pt}
        \renewcommand{\footrulewidth}{0pt}
