project:
  type: book

book:
  title: "Apuntes de programación en Rust"
  author: "Miguel A. Ortuño Pérez"
  date: today
  cover-image: portada.png
  chapters:
    - index.qmd
    - 02-intro_rust.qmd
    - 03-entorno.qmd
    - 04-fundamentos.qmd
    - 05-vbles-ctes-tbasicos.qmd
    - 06-tipos_compuestos.qmd
    - 07-funciones.qmd
    - 08-control_flujo.qmd
    - 09-propiedad.qmd
    - 10-structs.qmd
    - 11-metodos.qmd
    - 12-enum.qmd
    - 13-patrones.qmd
    - 14-vectores.qmd
    - 15-string.qmd
    - 16-hashmap.qmd
    - 17-manejo_errores.qmd
    - 18-entrada_salida.qmd
    - 19-modulos.qmd
    - 20-lifetimes.qmd
    - 21-test_automaticos.qmd


lang: es-ES

language:
  title-block-author-single: "Autor"
  title-block-author-plural: "Autores"

crossref:
  chapters: true

format:
  html:
    toc: true
    number-sections: true
    code-copy: true

  pdf:
    include-in-header: templates/header.tex
    template-partials:
      - templates/before-body.tex
    documentclass: scrreprt
    classoption:
      - twoside
      - titlepage

    fontsize: 13pt

    geometry:
      - top=3.0cm
      - bottom=2.5cm
      - left=2.2cm
      - right=2.2cm

    highlight-style: tango
    linestretch: 1.05
    number-sections: true
    papersize: a4
    pdf-engine: xelatex

    toc: true
    toc-title: Índice

    lot: true
